routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@main');
Route::get('about', 'PageController@about');

Route::resource('articles', 'ArticleController');

Route::get('search', 'PageController@search');

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'body'];

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use Illuminate\Http\Request;
use Illuminate\View\View;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index(): View
    {
        $articles = Article::paginate(5);
        return view('article.index', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create(): View
    {
        $article = new Article();
        return view('article.create', compact('article'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse|View
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $data = $this->validate(
            $request,
            [
                'title' => 'required|unique:articles',
                'body' => 'required|min:100',
            ]
        );

        $article = new Article();
        $article->fill($data);
        $article->save();

        return redirect()
            ->route('articles.index')
            ->with('status', 'Article was added successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Article $article
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|View
     */
    public function show(Article $article)
    {
        return view('article.show', compact('article'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Article $article
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response|View
     */
    public function edit(Article $article)
    {
        return view('article.edit', compact('article'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\Article      $article
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, Article $article)
    {
        $data = $this->validate(
            $request,
            [
                'title' => 'required|unique:articles,title,' . $article->id,
                'body' => 'required|min:100',
            ]
        );
        $article->fill($data);
        $article->save();

        return redirect()
            ->route('articles.index', ['article' => $article])
            ->with('status', 'Article is updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Article $article
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Article $article): \Illuminate\Http\RedirectResponse
    {
        if ($article) {
            $article->delete();
        }

        return redirect()
            ->route('articles.index')
            ->with('status', 'Article was deleted');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PageController.php
<?php


namespace App\Http\Controllers;


use App\Models\Article;
use Illuminate\Http\Request;

class PageController extends Controller
{
    public function main()
    {
        return view('page.main');
    }

    public function about()
    {
        return view('page.about');
    }

    public function search(Request $request)
    {
        $key = trim($request->get('q'));
        $articles = Article::query()
            ->where('title', 'like', "%{$key}%")
            ->orWhere('body', 'like', "%{$key}%")
            ->orderBy('created_at', 'desc')
            ->get();

        return view('page.search', compact('articles', 'key'));
    }
}

resources/views/article/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        {{ Form::model($article, ['url' => route('articles.store')]) }}
        @include('article.form')
        {{ Form::submit('Создать') }}
        {{ Form::close() }}
    </div>
@endsection

resources/views/article/edit.blade.php
@extends('layouts.app')

@section('content')

    {{ Form::model($article, ['url' => route('articles.update', $article), 'method' => 'PATCH']) }}
    @include('article.form')
    {{ Form::submit('Обновить') }}
    {{ Form::close() }}
@endsection

resources/views/article/form.blade.php
@if ($errors->any())
    <div>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<div class="form-group">
    {{ Form::label('title', 'Название', ['size' => 200]) }}
    {{ Form::text('title') }}<br>
</div>
<div class="form-group">
    {{ Form::label('body', 'Содержание') }}
    {{ Form::textarea('body') }}<br>
</div>

resources/views/article/index.blade.php
@extends('layouts.app')

@section('content')
    <h1 class="display-4 text-center">Список статей</h1>
    <h3 class="my-3">
        <a href="{{route('articles.create')}}"
           class="fa fa-newspaper-o btn btn-success" role="button"> Create new</a>
    </h3>
    <ul class="list-unstyled">
        <li class="media">
            <div class="media-body">
                @foreach ($articles as $article)
                    <h2 class="mt-0 mb-1 font-weight-bold">
                        <a href="{{ route('articles.show', $article) }}">{{$article->title}}</a>
                    </h2>
                    <div class="mb-4 text-break">{{Str::limit($article->body, 300)}}</div>
                    <h6 class="text-right">
                        <a href="{{ route('articles.destroy', $article) }}"
                           data-confirm="Вы уверены?"
                           data-method="delete" class="fa fa-remove btn btn-outline-danger text-danger"
                           rel="nofollow">
                            Delete
                        </a>
                    </h6>

                @endforeach
            </div>
        </li>
    </ul>

    <ul class="pagination justify-content-center mb-4">
        {{ $articles->links("pagination::bootstrap-4") }}
    </ul>
@endsection

resources/views/article/show.blade.php
@extends('layouts.app')

@section('content')
    <h1>{{$article->title}}</h1>
    <div class="text-break">{{$article->body}}</div>
    <h5 class="mt-4 fa fa-edit fa-lg"><a href="{{route('articles.edit', $article)}}"> Редактировать статью</a></h5>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Talent Online - @yield('title')</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="csrf-param" content="_token"/>
    <script src="{{ asset('js/app.js') }}" defer></script>
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>

<body>
<div class="bg-primary">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" href="/">Classic CRUD</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('articles.index') }}">Articles</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="about">About</a>
                    </li>
                </ul>
                <form action="search" method="get" class="form-inline my-2 my-lg-0">
                    {{ csrf_field() }}
                    <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </div>
</div>

<div class="container mt-4">
    <h1 class="bg-info">@yield('header')</h1>
    <div class="bg-light">
        @yield('content')
    </div>
</div>
</body>
</html>

resources/views/page/about.blade.php
@extends('layouts.app')

@section('content')
    <div class="text-center d-flex flex-column justify-content-center">
        <h3 class="mb-4">Данный проект ялвяет собой пример классического CRUD приложения.</h3>
        <p class="h4">Созданный специально для компании
            <a href="https://talentonline.eu/" target="_blank">Talent Online</a>
            <span class="fa fa-external-link text-primary"></span>
        </p>
        <p class="h5 mt-5">
            <span class="font-weight-bold text-secondary">Автор:</span> <span>Бачевский Юрий</span>
        </p>
        <a href="https://github.com/yur-ok" target="_blank">
            <span class="fa fa-github-alt fa-4x text-primary"></span>
        </a>
    </div>
@endsection

resources/views/page/main.blade.php
@extends('layouts.app')

@section('content')
    <h2 class="text-center mb-5">Главная станица проекта</h2>
    <p class="h4 text-break col-10">
        Данный учебный проект демонстрирует пример классичесокго CRUD-приложения. <br>
        В котором реализован базовый функционал для работы с сущностью проекта. <br>
        В данном примере сущность представленна в виде статьи.
    </p>

    <p class="h4 col-10">
        На примере статьи продемонстрированы базовые операции:
        <ul class="h4 list-group">
            <li class="list-group-item"><span class="font-weight-bolder text-primary">C</span>reate</li>
            <li class="list-group-item"><span class="font-weight-bolder text-primary">R</span>ead</li>
            <li class="list-group-item"><span class="font-weight-bolder text-primary">U</span>pdate</li>
            <li class="list-group-item"><span class="font-weight-bolder text-primary">D</span>elete</li>
        </ul>
    </p>
@endsection

resources/views/page/search.blade.php
@extends('layouts.app')

@section('content')
    <h2>You request <span class="font-weight-bold">{{ $key }}</span> found in:</h2>

    <div class="media-body">
        @foreach ($articles as $article)
            <h2 class="mt-0 mb-1 font-weight-bold">
                <a href="{{ route('articles.show', $article) }}">{{$article->title}}</a>
            </h2>
            <div class="mb-4 text-break">{{Str::limit($article->body, 300)}}</div>
            <h6 class="text-right">
                <a href="{{ route('articles.destroy', $article) }}"
                   data-confirm="Вы уверены?"
                   data-method="delete" class="fa fa-remove btn btn-outline-danger text-danger"
                   rel="nofollow">
                    Delete
                </a>
            </h6>

        @endforeach
    </div>
@endsection